USE [master]
GO

/****** Object:  Database [UMS]    Script Date: 4/16/2015 5:05:32 PM ******/
CREATE DATABASE [UMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL\MSSQL\DATA\UMS.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQL\MSSQL\DATA\UMS_log.ldf' , SIZE = 528KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UMS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [UMS] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [UMS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UMS] SET  ENABLE_BROKER 
GO

ALTER DATABASE [UMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [UMS] SET  MULTI_USER 
GO

ALTER DATABASE [UMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UMS] SET  READ_WRITE 
GO


